# Максимальная длина строки.
line-length = 99

# Список игнорируемых директорий и файлов.
exclude = ["migrations",]

[lint]
# Список групп правил, применяемых при проверке кода.
# E - Стилистика кода (отступы, пробелы и т.д.);
# F - Логические ошибки и недочеты (неиспользуемые импорты и переменные, опечатки в именах и т.д.);
# I - Порядок импортов.
select = ["E", "F", "I"]

[format]
# Использование одинарных кавычек.
quote-style = "single"
# Использование запятой после последнего объекта в многострочной итерируемой структуре или аргументе функции.
skip-magic-trailing-comma = false

[lint.isort]
# Объединяет все импорты из одного места в одну строку.
combine-as-imports = true
# Местоположение модулей проекта.
known-first-party = ["app"]
