[pytest]
# Режим тестирования асинхронного кода.
# - auto - pytest сам пытается определить асинхронные тесты (возможны ошибки);
# - strict - требует явной маркировки асинхронных тестов декоратором @pytest.mark.asyncio.
asyncio_mode = auto

# Добавление корневой директории проекта в пути импорта
# для возможности импорта тестами модулей из 'app'.
pythonpath = .
